### ISSUE TITLE
New update breaks plugin connection

### ISSUE THREAD

**Issue by p4cm4n** [Touch-Portal-MSFS/MSFSTouchPortalPlugin#30] opened 2021-03-20 09:57 UTC
**Describe the bug**
As discussed in TP's discord with Ty_Touch-Portal, the new layout update breaks this plugin, also many people is needing to launch MSFS and TP as admin to make it work.

**To Reproduce**
1. Open TP
2. Connect to ipad
3. game not connecting

**Expected behavior**
Expected the app to connect automatically, launching the plugins simconnect exe from command line works. from the path %AppData%\TouchPortal\plugins\MSFS-TouchPortal-Plugin\dist>MSFSTouchPortalPlugin.exe

**Plugin Version**
0.5.2

**Screenshots**
manual connection:
![image](https://user-images.githubusercontent.com/348831/111913840-f3ba2e00-8a6f-11eb-831b-7c652640f736.png)

**Comment by cusance** [comment] 2021-03-20 12:31
I agree. The touch portal plugin 5.2 no longer works.

**Comment by p4cm4n** [comment] 2021-03-21 11:33
We found out that launching manually the exe from \AppData\Roaming\TouchPortal\plugins\MSFS-TouchPortal-Plugin\dist\ works fine :)

**Comment by cusance** [comment] 2021-03-21 13:21
no sorry doesnt work for me. I use it only to get vital stats back onto the IOS touch portal like HDG, ALT, GrnD SPEED etc.
Dont know about layout issues as I dont use the page but the plugin no longer connects to MSFS whether started as plugin by TP or the EXE started manually as described above.

**Comment by p4cm4n** [comment] 2021-03-21 17:00
true, the layout is each user's problem, i'll try to update the issue to better reflect the connection problems :)

**Comment by tlewis17** [comment] 2021-03-21 20:14
Try running it manually by:

`MSFSTouchPortalPlugin.exe >> log.txt`

Attempt a few things like launching MSFS, get in a plane, push a few buttons. Then provide the log file. 
Remember that if MSFS is running as admin, the plugin has to be running as Admin (and possibly Touch Portal as well).

**Comment by cusance** [comment] 2021-03-22 10:23
thanks,
at the moment it doesnt connect at all.
at least for me.

**Comment by cusance** [comment] 2021-03-22 15:22
actually I dont think I will bother. As you can see from the screengrab I only use the plugin to get some info back
like HDG, speed etc. But I have several Logitech instrument panels working perfectly with SpadNext that give me all this info so I think I will just forget about this plugin for now. I have tried all different ways to connect. Check all authorities, started manually, actually got it to work once but then repeating that same sequence, it didnt work.
I have spend now enough time on this. I will wait a few months and then maybe come back to it.
All other plugins work fine like OBS etc so it gives me all I need. Eventually I am sure it will work, but not for me now.
![page](https://user-images.githubusercontent.com/81021697/112013939-5ec43d00-8b22-11eb-9cb6-102aa4240aaa.jpg)

**Comment by cusance** [comment] 2021-03-22 20:39
update: I can now get the plugin connected if I do the following:
(all running as administrator)
after reboot or initial PC start:
manually run the plugin.exe
then touchportal
than msfs
So I confirm that it will connect after a manual run.

however if I then close touch portal and msfs and later try this again, the plugin wont connect
unless I reboot the PC..
Not very practical but this is all I can do on this.
No idea how to fix this but the guys from Touch Portal have confirmed
that plugins need to be modified.
No idea how.
The VLC plugin also was modified.

**Comment by p4cm4n** [comment] 2021-03-22 22:58
The plugin appears in the details page of task manager, you can close it
from there without the need to reboot, also i managed to run it without
administrator account, maybe because i am admin in my system? IDK

**Comment by cusance** [comment] 2021-03-22 23:08
yes same here.
I know I can close it like that but it would be nice if someone could adjust whatever is needed, to make this run correctly.
i don't see that it will run correctly for anyone on the new version of TP.
Its beyond my abilities I fear.

**Comment by p4cm4n** [comment] 2021-03-22 23:20
yes, but that may (or may not) help debugging the problem, at least will
help if somebody who is in the same place as us :)

**Comment by tlewis17** [comment] 2021-03-22 23:50
The exe that runs will auto reconnect to MSFS without having to restart. That is handled without anything to do with Touch Portal. However, there is code specifically in there that when Touch Portal tells the program to close, it should close. Maybe something to do with that. I'll check out that specific part because I could see that causing an issue based on the situation you described.

**Comment by cusance** [comment] 2021-03-23 00:40
thanks
to be clear, the plugin does not connect with MSFS on opening TP.
It now needs to be started manually.
Once active it WILL disconnect when MSFS closes, obviously,  and will reconnect again when MSFS is restarted as long as TP wasn't shut down.
(I do note that VLC had a similar issue but that threw a script error message after the update of TP  and was fixed quickly.)
But even when started manually and functioning well, once TP has been closed and then reopened, the plugin doesnt connect, and cant be restarted manually either unless PC is rebooted or the plugin is closed via taskmaster first.
Clever stuff if you understand all this, its mystifying to me  😣

**Comment by tlewis17** [comment] 2021-03-23 04:04
Interesting. But yes, it only attempts connecting to TP once and that is once the Plugin starts. I think the auto start might be broken. I'll look into it in a day or two, busy studying for an exam for Tuesday.

**Comment by cusance** [comment] 2021-03-23 09:55
well thats a lot more important than the plugin. 
Good luck.

**Comment by p4cm4n** [comment] 2021-03-24 07:35
First things first, hope you’re lucky with your exam bro :)

**Comment by cusance** [comment] 2021-03-29 14:15
UPDATE: I am not sure you need to do anything with the plugin.
At least for me since the TP V2.3.006 the plugin connects correctly as it should by starting the TP.
No need anymore for manual start.
So whatever happened with the TP updates (there were a few in rapid succession) seems to have fixed the connection
issues of the MSFS plugin.

**Comment by tlewis17** [comment] 2021-04-06 06:42
Update:
I think I found the cause. TP no longer sends "ClosePlugin" commands if you exit from the tray icon. Maybe other places too. So that leaves the plugin running. Also, what that means is that when it starts up again it launches another instance of the plugin which terminates itself as there is code in place to ensure only one instance is running. 

Further, if it is still running and TP isn't, it has lost the connection to TP. It only ever attempts to connect to TP on startup. 

So I have 2 fixes that I'm working on for the 0.5.3 release coming up. 

1. If TP connection fails, exit plugin.
2. On startup, if unable to connect to TP, exit. 

This will tie the lifecycle of the plugin to TP at all times. Meaning, you shouldn't ever have a scenario where the Plugin is running without TP already running. Also note, the start/stop from TP's plugin settings should properly close and restart the plugin.

**Comment by cusance** [comment] 2021-04-06 08:44
great job, 
it sounds to me that you have found the perfect solution.
thanks.

**Closed** 2021-04-13 06:21 UTC
Labels: bug

**Comment by p4cm4n** [comment] 2021-04-13 06:57
yeaaah! :D
